# Generated by Django 5.1 on 2024-12-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminario_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='correo',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='estado',
            field=models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO ASISTEN', 'No Asisten')], default='RESERVADO', max_length=20),
        ),
    ]
